id_mappings = {
    '1': '1', 
    '2': '2', 
    '3': '3', 
    '4': '4', 
    '5': '5', 
    '6': '6', 
    '7': '7', 
    '8': '8', 
    '9': '9',
    "01": lambda condition: f"move_forward({condition})",
    "02": lambda condition: f"move_backward({condition})",
    "03": lambda condition: f"turn_left({condition})",
    "04": lambda condition: f"turn_right({condition})",
    "05": lambda condition: f"stop({condition})",
    "06": lambda condition: f"wait({condition})",
    "07": lambda condition: f"quack({condition})",
    "08": lambda condition: f"if({condition})",
    "09": lambda condition: f"elif({condition})",
    "10": lambda condition: f"else({condition})",
    "11": lambda condition: f"end-if({condition})",
    "12": lambda condition: f"end-elif({condition})",
    "13": lambda condition: f"end-else({condition})",
    "14": lambda condition: f"obstacle_front({condition})",
    "15": lambda condition: f"more_than({condition})",
    "16": lambda condition: f"less_than({condition})",
    "17": lambda condition: f"equal_to({condition})",
    "18": lambda condition: f"clap({condition})"
}